version: "3"

services:
  nginx:
    image: nginx:1-alpine
    env_file: .env
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html:rw,cached
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true

  php:
    build: docker/php
    env_file: .env
    volumes:
      - .:/var/www/html:rw,cached
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    tty: true
